# Generated by Django 5.0.7 on 2024-07-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='media')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('log_date', models.DateTimeField(auto_now=True)),
                ('log_state', models.BooleanField(default=False)),
            ],
        ),
    ]
